"use strict";
const http = require("http");
const { MongoClient } = require("mongodb");
const PORT = Number(process.env.PORT || 5005);
const HOST = process.env.HOST || "0.0.0.0";
const MONGO_URI = process.env.MONGO_URI || "mongodb://127.0.0.1:27017";
const DB_NAME = process.env.MONGO_DB || "payment_db";
const ALLOWED_METHODS = new Set(["MOMO", "VNPAY", "CASH"]);
const MAX_BODY_BYTES = 1024 * 1024;
function corsHeaders() { return { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET,POST,OPTIONS", "Access-Control-Allow-Headers": "Content-Type,Authorization", "Access-Control-Max-Age": "86400" }; }
function sendJson(res, statusCode, payload) { const body = JSON.stringify(payload); res.writeHead(statusCode, { ...corsHeaders(), "Content-Type": "application/json; charset=utf-8", "Content-Length": Buffer.byteLength(body) }); res.end(body); }
function sendError(res, statusCode, message) { sendJson(res, statusCode, { error: message }); }
function readJsonBody(req) { return new Promise((resolve, reject) => { let raw = "", bytes = 0; req.setEncoding("utf8"); req.on("data", chunk => { bytes += Buffer.byteLength(chunk); if (bytes > MAX_BODY_BYTES) { reject(Object.assign(new Error("Request body quá lớn"), { statusCode: 413 })); req.destroy(); return; } raw += chunk; }); req.on("end", () => { try { resolve(JSON.parse(raw)); } catch (_) { reject(Object.assign(new Error("JSON không hợp lệ"), { statusCode: 400 })); } }); req.on("error", reject); }); }
function validateShape(input) { if (!input || typeof input !== "object" || Array.isArray(input)) return "Body phải là một object JSON"; if (!Number.isInteger(input.bookingId) || input.bookingId <= 0) return "bookingId phải là số nguyên dương"; if (typeof input.amount !== "number" || !Number.isFinite(input.amount)) return "amount phải là số"; if (typeof input.method !== "string" || input.method.trim() === "") return "method là bắt buộc"; return null; }
function normalizeTransaction(input) { const method = String(input.method).trim().toUpperCase(); return { bookingId: Number(input.bookingId), amount: Number(input.amount), method, status: input.amount > 0 && ALLOWED_METHODS.has(method) ? "PAID" : "FAILED", paidAt: new Date() }; }
function serializeTransaction(doc) { return { ...doc, _id: doc._id ? String(doc._id) : undefined, paidAt: doc.paidAt instanceof Date ? doc.paidAt.toISOString() : doc.paidAt }; }
function createApp(collection) { return http.createServer(async (req, res) => { if (req.method === "OPTIONS") { res.writeHead(204, corsHeaders()); return res.end(); } const path = new URL(req.url, `http://${req.headers.host || "localhost"}`).pathname; try { if (path === "/api/payment" && req.method === "POST") { const input = await readJsonBody(req); const shapeError = validateShape(input); if (shapeError) return sendError(res, 400, shapeError); const transaction = normalizeTransaction(input); const result = await collection.insertOne(transaction); return sendJson(res, 201, { message: transaction.status === "PAID" ? "Thanh toán thành công" : "Thanh toán thất bại", transaction: serializeTransaction({ ...transaction, _id: result.insertedId }) }); } if (path === "/api/payment" && req.method === "GET") { const transactions = await collection.find({}).sort({ paidAt: -1 }).toArray(); return sendJson(res, 200, transactions.map(serializeTransaction)); } if (path === "/health" && req.method === "GET") return sendJson(res, 200, { status: "ok", service: "payment-service" }); return sendError(res, 404, "Không tìm thấy endpoint"); } catch (error) { console.error("[payment-service] request error:", error); return sendError(res, error.statusCode || 500, error.statusCode ? error.message : "Lỗi máy chủ nội bộ"); } }); }
async function start() { const client = new MongoClient(MONGO_URI); await client.connect(); const collection = client.db(DB_NAME).collection("transactions"); await collection.createIndex({ bookingId: 1 }); const server = createApp(collection); server.listen(PORT, HOST, () => console.log(`Payment Service đang chạy tại http://${HOST}:${PORT}`)); const shutdown = signal => { console.log(`Nhận ${signal}, đang đóng Payment Service...`); server.close(async () => { await client.close(); process.exit(0); }); }; process.once("SIGINT", () => shutdown("SIGINT")); process.once("SIGTERM", () => shutdown("SIGTERM")); return { server, client }; }
if (require.main === module) start().catch(error => { console.error("Không thể khởi động Payment Service:", error.message); process.exit(1); });
module.exports = { ALLOWED_METHODS, createApp, normalizeTransaction, validateShape };
